name: Questions
description: General questions about the work
title: "[Question] "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in our work.  Please feel free to raise your questions below. :)
  - type: textarea
    id: question
    attributes:
      label: Question
      placeholder: Start question here...